In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame([range(1,20), range(10,30), range(20,40), range(30,45), range(40,60), range(50,60), range(50,65)]*4, columns=["id"] + ["x"+str(i) for i in range(18)] + ["y"])

In [3]:
df

,id,x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,x11,x12,x13,x14,x15,x16,x17,y
0,1,2,3,4,5,6,7,8,9,10,11.0,12.0,13.0,14.0,15.0,16.0,17.0,18.0,19.0,NaN
1,10,11,12,13,14,15,16,17,18,19,20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,29.0
2,20,21,22,23,24,25,26,27,28,29,30.0,31.0,32.0,33.0,34.0,35.0,36.0,37.0,38.0,39.0
3,30,31,32,33,34,35,36,37,38,39,40.0,41.0,42.0,43.0,44.0,NaN,NaN,NaN,NaN,NaN
4,40,41,42,43,44,45,46,47,48,49,50.0,51.0,52.0,53.0,54.0,55.0,56.0,57.0,58.0,59.0
5,50,51,52,53,54,55,56,57,58,59,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,50,51,52,53,54,55,56,57,58,59,60.0,61.0,62.0,63.0,64.0,NaN,NaN,NaN,NaN,NaN
7,1,2,3,4,5,6,7,8,9,10,11.0,12.0,13.0,14.0,15.0,16.0,17.0,18.0,19.0,NaN
8,10,11,12,13,14,15,16,17,18,19,20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,29.0
9,20,21,22,23,24,25,26,27,28,29,30.0,31.0,32.0,33.0,34.0,35.0,36.0,37.0,38.0,39.0
10,30,31,32,33,34,35,36,37,38,39,40.0,41.0,42.0,43.0,44.0,NaN,NaN,NaN,NaN,NaN
11,40,41,42,43,44,45,46,47,48,49,50.0,51.0,52.0,53.0,54.0,55.0,56.0,57.0,58.0,59.0
12,50,51,52,53,54,55,56,57,58,59,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,50,51,52,53,54,55,56,57,58,59,60.0,61.0,62.0,63.0,64.0,NaN,NaN,NaN,NaN,NaN
14,1,2,3,4,5,6,7,8,9,10,11.0,12.0,13.0,14.0,15.0,16.0,17.0,18.0,19.0,NaN
15,10,11,12,13,14,15,16,17,18,19,20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,29.0
16,20,21,22,23,24,25,26,27,28,29,30.0,31.0,32.0,33.0,34.0,35.0,36.0,37.0,38.0,39.0
17,30,31,32,33,34,35,36,37,38,39,40.0,41.0,42.0,43.0,44.0,NaN,NaN,NaN,NaN,NaN
18,40,41,42,43,44,45,46,47,48,49,50.0,51.0,52.0,53.0,54.0,55.0,56.0,57.0,58.0,59.0
19,50,51,52,53,54,55,56,57,58,59,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,50,51,52,53,54,55,56,57,58,59,60.0,61.0,62.0,63.0,64.0,NaN,NaN,NaN,NaN,NaN
21,1,2,3,4,5,6,7,8,9,10,11.0,12.0,13.0,14.0,15.0,16.0,17.0,18.0,19.0,NaN
22,10,11,12,13,14,15,16,17,18,19,20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,29.0
23,20,21,22,23,24,25,26,27,28,29,30.0,31.0,32.0,33.0,34.0,35.0,36.0,37.0,38.0,39.0
24,30,31,32,33,34,35,36,37,38,39,40.0,41.0,42.0,43.0,44.0,NaN,NaN,NaN,NaN,NaN
25,40,41,42,43,44,45,46,47,48,49,50.0,51.0,52.0,53.0,54.0,55.0,56.0,57.0,58.0,59.0
26,50,51,52,53,54,55,56,57,58,59,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,50,51,52,53,54,55,56,57,58,59,60.0,61.0,62.0,63.0,64.0,NaN,NaN,NaN,NaN,NaN

In [4]:
df.replace('Nan',0)

,id,x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,x11,x12,x13,x14,x15,x16,x17,y
0,1,2,3,4,5,6,7,8,9,10,11.0,12.0,13.0,14.0,15.0,16.0,17.0,18.0,19.0,NaN
1,10,11,12,13,14,15,16,17,18,19,20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,29.0
2,20,21,22,23,24,25,26,27,28,29,30.0,31.0,32.0,33.0,34.0,35.0,36.0,37.0,38.0,39.0
3,30,31,32,33,34,35,36,37,38,39,40.0,41.0,42.0,43.0,44.0,NaN,NaN,NaN,NaN,NaN
4,40,41,42,43,44,45,46,47,48,49,50.0,51.0,52.0,53.0,54.0,55.0,56.0,57.0,58.0,59.0
5,50,51,52,53,54,55,56,57,58,59,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,50,51,52,53,54,55,56,57,58,59,60.0,61.0,62.0,63.0,64.0,NaN,NaN,NaN,NaN,NaN
7,1,2,3,4,5,6,7,8,9,10,11.0,12.0,13.0,14.0,15.0,16.0,17.0,18.0,19.0,NaN
8,10,11,12,13,14,15,16,17,18,19,20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,29.0
9,20,21,22,23,24,25,26,27,28,29,30.0,31.0,32.0,33.0,34.0,35.0,36.0,37.0,38.0,39.0
10,30,31,32,33,34,35,36,37,38,39,40.0,41.0,42.0,43.0,44.0,NaN,NaN,NaN,NaN,NaN
11,40,41,42,43,44,45,46,47,48,49,50.0,51.0,52.0,53.0,54.0,55.0,56.0,57.0,58.0,59.0
12,50,51,52,53,54,55,56,57,58,59,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,50,51,52,53,54,55,56,57,58,59,60.0,61.0,62.0,63.0,64.0,NaN,NaN,NaN,NaN,NaN
14,1,2,3,4,5,6,7,8,9,10,11.0,12.0,13.0,14.0,15.0,16.0,17.0,18.0,19.0,NaN
15,10,11,12,13,14,15,16,17,18,19,20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,29.0
16,20,21,22,23,24,25,26,27,28,29,30.0,31.0,32.0,33.0,34.0,35.0,36.0,37.0,38.0,39.0
17,30,31,32,33,34,35,36,37,38,39,40.0,41.0,42.0,43.0,44.0,NaN,NaN,NaN,NaN,NaN
18,40,41,42,43,44,45,46,47,48,49,50.0,51.0,52.0,53.0,54.0,55.0,56.0,57.0,58.0,59.0
19,50,51,52,53,54,55,56,57,58,59,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,50,51,52,53,54,55,56,57,58,59,60.0,61.0,62.0,63.0,64.0,NaN,NaN,NaN,NaN,NaN
21,1,2,3,4,5,6,7,8,9,10,11.0,12.0,13.0,14.0,15.0,16.0,17.0,18.0,19.0,NaN
22,10,11,12,13,14,15,16,17,18,19,20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,29.0
23,20,21,22,23,24,25,26,27,28,29,30.0,31.0,32.0,33.0,34.0,35.0,36.0,37.0,38.0,39.0
24,30,31,32,33,34,35,36,37,38,39,40.0,41.0,42.0,43.0,44.0,NaN,NaN,NaN,NaN,NaN
25,40,41,42,43,44,45,46,47,48,49,50.0,51.0,52.0,53.0,54.0,55.0,56.0,57.0,58.0,59.0
26,50,51,52,53,54,55,56,57,58,59,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,50,51,52,53,54,55,56,57,58,59,60.0,61.0,62.0,63.0,64.0,NaN,NaN,NaN,NaN,NaN

In [5]:
df.replace(1,10)

,id,x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,x11,x12,x13,x14,x15,x16,x17,y
0,10,2,3,4,5,6,7,8,9,10,11.0,12.0,13.0,14.0,15.0,16.0,17.0,18.0,19.0,NaN
1,10,11,12,13,14,15,16,17,18,19,20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,29.0
2,20,21,22,23,24,25,26,27,28,29,30.0,31.0,32.0,33.0,34.0,35.0,36.0,37.0,38.0,39.0
3,30,31,32,33,34,35,36,37,38,39,40.0,41.0,42.0,43.0,44.0,NaN,NaN,NaN,NaN,NaN
4,40,41,42,43,44,45,46,47,48,49,50.0,51.0,52.0,53.0,54.0,55.0,56.0,57.0,58.0,59.0
5,50,51,52,53,54,55,56,57,58,59,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,50,51,52,53,54,55,56,57,58,59,60.0,61.0,62.0,63.0,64.0,NaN,NaN,NaN,NaN,NaN
7,10,2,3,4,5,6,7,8,9,10,11.0,12.0,13.0,14.0,15.0,16.0,17.0,18.0,19.0,NaN
8,10,11,12,13,14,15,16,17,18,19,20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,29.0
9,20,21,22,23,24,25,26,27,28,29,30.0,31.0,32.0,33.0,34.0,35.0,36.0,37.0,38.0,39.0
10,30,31,32,33,34,35,36,37,38,39,40.0,41.0,42.0,43.0,44.0,NaN,NaN,NaN,NaN,NaN
11,40,41,42,43,44,45,46,47,48,49,50.0,51.0,52.0,53.0,54.0,55.0,56.0,57.0,58.0,59.0
12,50,51,52,53,54,55,56,57,58,59,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,50,51,52,53,54,55,56,57,58,59,60.0,61.0,62.0,63.0,64.0,NaN,NaN,NaN,NaN,NaN
14,10,2,3,4,5,6,7,8,9,10,11.0,12.0,13.0,14.0,15.0,16.0,17.0,18.0,19.0,NaN
15,10,11,12,13,14,15,16,17,18,19,20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,29.0
16,20,21,22,23,24,25,26,27,28,29,30.0,31.0,32.0,33.0,34.0,35.0,36.0,37.0,38.0,39.0
17,30,31,32,33,34,35,36,37,38,39,40.0,41.0,42.0,43.0,44.0,NaN,NaN,NaN,NaN,NaN
18,40,41,42,43,44,45,46,47,48,49,50.0,51.0,52.0,53.0,54.0,55.0,56.0,57.0,58.0,59.0
19,50,51,52,53,54,55,56,57,58,59,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,50,51,52,53,54,55,56,57,58,59,60.0,61.0,62.0,63.0,64.0,NaN,NaN,NaN,NaN,NaN
21,10,2,3,4,5,6,7,8,9,10,11.0,12.0,13.0,14.0,15.0,16.0,17.0,18.0,19.0,NaN
22,10,11,12,13,14,15,16,17,18,19,20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,29.0
23,20,21,22,23,24,25,26,27,28,29,30.0,31.0,32.0,33.0,34.0,35.0,36.0,37.0,38.0,39.0
24,30,31,32,33,34,35,36,37,38,39,40.0,41.0,42.0,43.0,44.0,NaN,NaN,NaN,NaN,NaN
25,40,41,42,43,44,45,46,47,48,49,50.0,51.0,52.0,53.0,54.0,55.0,56.0,57.0,58.0,59.0
26,50,51,52,53,54,55,56,57,58,59,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,50,51,52,53,54,55,56,57,58,59,60.0,61.0,62.0,63.0,64.0,NaN,NaN,NaN,NaN,NaN

In [6]:
df.replace(10,1)

,id,x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,x11,x12,x13,x14,x15,x16,x17,y
0,1,2,3,4,5,6,7,8,9,1,11.0,12.0,13.0,14.0,15.0,16.0,17.0,18.0,19.0,NaN
1,1,11,12,13,14,15,16,17,18,19,20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,29.0
2,20,21,22,23,24,25,26,27,28,29,30.0,31.0,32.0,33.0,34.0,35.0,36.0,37.0,38.0,39.0
3,30,31,32,33,34,35,36,37,38,39,40.0,41.0,42.0,43.0,44.0,NaN,NaN,NaN,NaN,NaN
4,40,41,42,43,44,45,46,47,48,49,50.0,51.0,52.0,53.0,54.0,55.0,56.0,57.0,58.0,59.0
5,50,51,52,53,54,55,56,57,58,59,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,50,51,52,53,54,55,56,57,58,59,60.0,61.0,62.0,63.0,64.0,NaN,NaN,NaN,NaN,NaN
7,1,2,3,4,5,6,7,8,9,1,11.0,12.0,13.0,14.0,15.0,16.0,17.0,18.0,19.0,NaN
8,1,11,12,13,14,15,16,17,18,19,20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,29.0
9,20,21,22,23,24,25,26,27,28,29,30.0,31.0,32.0,33.0,34.0,35.0,36.0,37.0,38.0,39.0
10,30,31,32,33,34,35,36,37,38,39,40.0,41.0,42.0,43.0,44.0,NaN,NaN,NaN,NaN,NaN
11,40,41,42,43,44,45,46,47,48,49,50.0,51.0,52.0,53.0,54.0,55.0,56.0,57.0,58.0,59.0
12,50,51,52,53,54,55,56,57,58,59,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,50,51,52,53,54,55,56,57,58,59,60.0,61.0,62.0,63.0,64.0,NaN,NaN,NaN,NaN,NaN
14,1,2,3,4,5,6,7,8,9,1,11.0,12.0,13.0,14.0,15.0,16.0,17.0,18.0,19.0,NaN
15,1,11,12,13,14,15,16,17,18,19,20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,29.0
16,20,21,22,23,24,25,26,27,28,29,30.0,31.0,32.0,33.0,34.0,35.0,36.0,37.0,38.0,39.0
17,30,31,32,33,34,35,36,37,38,39,40.0,41.0,42.0,43.0,44.0,NaN,NaN,NaN,NaN,NaN
18,40,41,42,43,44,45,46,47,48,49,50.0,51.0,52.0,53.0,54.0,55.0,56.0,57.0,58.0,59.0
19,50,51,52,53,54,55,56,57,58,59,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,50,51,52,53,54,55,56,57,58,59,60.0,61.0,62.0,63.0,64.0,NaN,NaN,NaN,NaN,NaN
21,1,2,3,4,5,6,7,8,9,1,11.0,12.0,13.0,14.0,15.0,16.0,17.0,18.0,19.0,NaN
22,1,11,12,13,14,15,16,17,18,19,20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,29.0
23,20,21,22,23,24,25,26,27,28,29,30.0,31.0,32.0,33.0,34.0,35.0,36.0,37.0,38.0,39.0
24,30,31,32,33,34,35,36,37,38,39,40.0,41.0,42.0,43.0,44.0,NaN,NaN,NaN,NaN,NaN
25,40,41,42,43,44,45,46,47,48,49,50.0,51.0,52.0,53.0,54.0,55.0,56.0,57.0,58.0,59.0
26,50,51,52,53,54,55,56,57,58,59,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,50,51,52,53,54,55,56,57,58,59,60.0,61.0,62.0,63.0,64.0,NaN,NaN,NaN,NaN,NaN

In [7]:
df.replace(Nan,0)

NameError: name 'Nan' is not defined

In [8]:
df.replace('',0)

,id,x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,x11,x12,x13,x14,x15,x16,x17,y
0,1,2,3,4,5,6,7,8,9,10,11.0,12.0,13.0,14.0,15.0,16.0,17.0,18.0,19.0,NaN
1,10,11,12,13,14,15,16,17,18,19,20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,29.0
2,20,21,22,23,24,25,26,27,28,29,30.0,31.0,32.0,33.0,34.0,35.0,36.0,37.0,38.0,39.0
3,30,31,32,33,34,35,36,37,38,39,40.0,41.0,42.0,43.0,44.0,NaN,NaN,NaN,NaN,NaN
4,40,41,42,43,44,45,46,47,48,49,50.0,51.0,52.0,53.0,54.0,55.0,56.0,57.0,58.0,59.0
5,50,51,52,53,54,55,56,57,58,59,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,50,51,52,53,54,55,56,57,58,59,60.0,61.0,62.0,63.0,64.0,NaN,NaN,NaN,NaN,NaN
7,1,2,3,4,5,6,7,8,9,10,11.0,12.0,13.0,14.0,15.0,16.0,17.0,18.0,19.0,NaN
8,10,11,12,13,14,15,16,17,18,19,20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,29.0
9,20,21,22,23,24,25,26,27,28,29,30.0,31.0,32.0,33.0,34.0,35.0,36.0,37.0,38.0,39.0
10,30,31,32,33,34,35,36,37,38,39,40.0,41.0,42.0,43.0,44.0,NaN,NaN,NaN,NaN,NaN
11,40,41,42,43,44,45,46,47,48,49,50.0,51.0,52.0,53.0,54.0,55.0,56.0,57.0,58.0,59.0
12,50,51,52,53,54,55,56,57,58,59,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,50,51,52,53,54,55,56,57,58,59,60.0,61.0,62.0,63.0,64.0,NaN,NaN,NaN,NaN,NaN
14,1,2,3,4,5,6,7,8,9,10,11.0,12.0,13.0,14.0,15.0,16.0,17.0,18.0,19.0,NaN
15,10,11,12,13,14,15,16,17,18,19,20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,29.0
16,20,21,22,23,24,25,26,27,28,29,30.0,31.0,32.0,33.0,34.0,35.0,36.0,37.0,38.0,39.0
17,30,31,32,33,34,35,36,37,38,39,40.0,41.0,42.0,43.0,44.0,NaN,NaN,NaN,NaN,NaN
18,40,41,42,43,44,45,46,47,48,49,50.0,51.0,52.0,53.0,54.0,55.0,56.0,57.0,58.0,59.0
19,50,51,52,53,54,55,56,57,58,59,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,50,51,52,53,54,55,56,57,58,59,60.0,61.0,62.0,63.0,64.0,NaN,NaN,NaN,NaN,NaN
21,1,2,3,4,5,6,7,8,9,10,11.0,12.0,13.0,14.0,15.0,16.0,17.0,18.0,19.0,NaN
22,10,11,12,13,14,15,16,17,18,19,20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,29.0
23,20,21,22,23,24,25,26,27,28,29,30.0,31.0,32.0,33.0,34.0,35.0,36.0,37.0,38.0,39.0
24,30,31,32,33,34,35,36,37,38,39,40.0,41.0,42.0,43.0,44.0,NaN,NaN,NaN,NaN,NaN
25,40,41,42,43,44,45,46,47,48,49,50.0,51.0,52.0,53.0,54.0,55.0,56.0,57.0,58.0,59.0
26,50,51,52,53,54,55,56,57,58,59,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,50,51,52,53,54,55,56,57,58,59,60.0,61.0,62.0,63.0,64.0,NaN,NaN,NaN,NaN,NaN

In [9]:
df.replace(,0)

SyntaxError: invalid syntax (2543746411.py, line 1)

In [10]:
df.replace('',0)

,id,x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,x11,x12,x13,x14,x15,x16,x17,y
0,1,2,3,4,5,6,7,8,9,10,11.0,12.0,13.0,14.0,15.0,16.0,17.0,18.0,19.0,NaN
1,10,11,12,13,14,15,16,17,18,19,20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,29.0
2,20,21,22,23,24,25,26,27,28,29,30.0,31.0,32.0,33.0,34.0,35.0,36.0,37.0,38.0,39.0
3,30,31,32,33,34,35,36,37,38,39,40.0,41.0,42.0,43.0,44.0,NaN,NaN,NaN,NaN,NaN
4,40,41,42,43,44,45,46,47,48,49,50.0,51.0,52.0,53.0,54.0,55.0,56.0,57.0,58.0,59.0
5,50,51,52,53,54,55,56,57,58,59,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,50,51,52,53,54,55,56,57,58,59,60.0,61.0,62.0,63.0,64.0,NaN,NaN,NaN,NaN,NaN
7,1,2,3,4,5,6,7,8,9,10,11.0,12.0,13.0,14.0,15.0,16.0,17.0,18.0,19.0,NaN
8,10,11,12,13,14,15,16,17,18,19,20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,29.0
9,20,21,22,23,24,25,26,27,28,29,30.0,31.0,32.0,33.0,34.0,35.0,36.0,37.0,38.0,39.0
10,30,31,32,33,34,35,36,37,38,39,40.0,41.0,42.0,43.0,44.0,NaN,NaN,NaN,NaN,NaN
11,40,41,42,43,44,45,46,47,48,49,50.0,51.0,52.0,53.0,54.0,55.0,56.0,57.0,58.0,59.0
12,50,51,52,53,54,55,56,57,58,59,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,50,51,52,53,54,55,56,57,58,59,60.0,61.0,62.0,63.0,64.0,NaN,NaN,NaN,NaN,NaN
14,1,2,3,4,5,6,7,8,9,10,11.0,12.0,13.0,14.0,15.0,16.0,17.0,18.0,19.0,NaN
15,10,11,12,13,14,15,16,17,18,19,20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,29.0
16,20,21,22,23,24,25,26,27,28,29,30.0,31.0,32.0,33.0,34.0,35.0,36.0,37.0,38.0,39.0
17,30,31,32,33,34,35,36,37,38,39,40.0,41.0,42.0,43.0,44.0,NaN,NaN,NaN,NaN,NaN
18,40,41,42,43,44,45,46,47,48,49,50.0,51.0,52.0,53.0,54.0,55.0,56.0,57.0,58.0,59.0
19,50,51,52,53,54,55,56,57,58,59,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,50,51,52,53,54,55,56,57,58,59,60.0,61.0,62.0,63.0,64.0,NaN,NaN,NaN,NaN,NaN
21,1,2,3,4,5,6,7,8,9,10,11.0,12.0,13.0,14.0,15.0,16.0,17.0,18.0,19.0,NaN
22,10,11,12,13,14,15,16,17,18,19,20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,29.0
23,20,21,22,23,24,25,26,27,28,29,30.0,31.0,32.0,33.0,34.0,35.0,36.0,37.0,38.0,39.0
24,30,31,32,33,34,35,36,37,38,39,40.0,41.0,42.0,43.0,44.0,NaN,NaN,NaN,NaN,NaN
25,40,41,42,43,44,45,46,47,48,49,50.0,51.0,52.0,53.0,54.0,55.0,56.0,57.0,58.0,59.0
26,50,51,52,53,54,55,56,57,58,59,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,50,51,52,53,54,55,56,57,58,59,60.0,61.0,62.0,63.0,64.0,NaN,NaN,NaN,NaN,NaN

In [11]:
df.replace('None',0)

,id,x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,x11,x12,x13,x14,x15,x16,x17,y
0,1,2,3,4,5,6,7,8,9,10,11.0,12.0,13.0,14.0,15.0,16.0,17.0,18.0,19.0,NaN
1,10,11,12,13,14,15,16,17,18,19,20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,29.0
2,20,21,22,23,24,25,26,27,28,29,30.0,31.0,32.0,33.0,34.0,35.0,36.0,37.0,38.0,39.0
3,30,31,32,33,34,35,36,37,38,39,40.0,41.0,42.0,43.0,44.0,NaN,NaN,NaN,NaN,NaN
4,40,41,42,43,44,45,46,47,48,49,50.0,51.0,52.0,53.0,54.0,55.0,56.0,57.0,58.0,59.0
5,50,51,52,53,54,55,56,57,58,59,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,50,51,52,53,54,55,56,57,58,59,60.0,61.0,62.0,63.0,64.0,NaN,NaN,NaN,NaN,NaN
7,1,2,3,4,5,6,7,8,9,10,11.0,12.0,13.0,14.0,15.0,16.0,17.0,18.0,19.0,NaN
8,10,11,12,13,14,15,16,17,18,19,20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,29.0
9,20,21,22,23,24,25,26,27,28,29,30.0,31.0,32.0,33.0,34.0,35.0,36.0,37.0,38.0,39.0
10,30,31,32,33,34,35,36,37,38,39,40.0,41.0,42.0,43.0,44.0,NaN,NaN,NaN,NaN,NaN
11,40,41,42,43,44,45,46,47,48,49,50.0,51.0,52.0,53.0,54.0,55.0,56.0,57.0,58.0,59.0
12,50,51,52,53,54,55,56,57,58,59,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,50,51,52,53,54,55,56,57,58,59,60.0,61.0,62.0,63.0,64.0,NaN,NaN,NaN,NaN,NaN
14,1,2,3,4,5,6,7,8,9,10,11.0,12.0,13.0,14.0,15.0,16.0,17.0,18.0,19.0,NaN
15,10,11,12,13,14,15,16,17,18,19,20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,29.0
16,20,21,22,23,24,25,26,27,28,29,30.0,31.0,32.0,33.0,34.0,35.0,36.0,37.0,38.0,39.0
17,30,31,32,33,34,35,36,37,38,39,40.0,41.0,42.0,43.0,44.0,NaN,NaN,NaN,NaN,NaN
18,40,41,42,43,44,45,46,47,48,49,50.0,51.0,52.0,53.0,54.0,55.0,56.0,57.0,58.0,59.0
19,50,51,52,53,54,55,56,57,58,59,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,50,51,52,53,54,55,56,57,58,59,60.0,61.0,62.0,63.0,64.0,NaN,NaN,NaN,NaN,NaN
21,1,2,3,4,5,6,7,8,9,10,11.0,12.0,13.0,14.0,15.0,16.0,17.0,18.0,19.0,NaN
22,10,11,12,13,14,15,16,17,18,19,20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,29.0
23,20,21,22,23,24,25,26,27,28,29,30.0,31.0,32.0,33.0,34.0,35.0,36.0,37.0,38.0,39.0
24,30,31,32,33,34,35,36,37,38,39,40.0,41.0,42.0,43.0,44.0,NaN,NaN,NaN,NaN,NaN
25,40,41,42,43,44,45,46,47,48,49,50.0,51.0,52.0,53.0,54.0,55.0,56.0,57.0,58.0,59.0
26,50,51,52,53,54,55,56,57,58,59,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,50,51,52,53,54,55,56,57,58,59,60.0,61.0,62.0,63.0,64.0,NaN,NaN,NaN,NaN,NaN

In [13]:
df.fillna(0)

,id,x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,x11,x12,x13,x14,x15,x16,x17,y
0,1,2,3,4,5,6,7,8,9,10,11.0,12.0,13.0,14.0,15.0,16.0,17.0,18.0,19.0,0.0
1,10,11,12,13,14,15,16,17,18,19,20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,29.0
2,20,21,22,23,24,25,26,27,28,29,30.0,31.0,32.0,33.0,34.0,35.0,36.0,37.0,38.0,39.0
3,30,31,32,33,34,35,36,37,38,39,40.0,41.0,42.0,43.0,44.0,0.0,0.0,0.0,0.0,0.0
4,40,41,42,43,44,45,46,47,48,49,50.0,51.0,52.0,53.0,54.0,55.0,56.0,57.0,58.0,59.0
5,50,51,52,53,54,55,56,57,58,59,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,50,51,52,53,54,55,56,57,58,59,60.0,61.0,62.0,63.0,64.0,0.0,0.0,0.0,0.0,0.0
7,1,2,3,4,5,6,7,8,9,10,11.0,12.0,13.0,14.0,15.0,16.0,17.0,18.0,19.0,0.0
8,10,11,12,13,14,15,16,17,18,19,20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,29.0
9,20,21,22,23,24,25,26,27,28,29,30.0,31.0,32.0,33.0,34.0,35.0,36.0,37.0,38.0,39.0
10,30,31,32,33,34,35,36,37,38,39,40.0,41.0,42.0,43.0,44.0,0.0,0.0,0.0,0.0,0.0
11,40,41,42,43,44,45,46,47,48,49,50.0,51.0,52.0,53.0,54.0,55.0,56.0,57.0,58.0,59.0
12,50,51,52,53,54,55,56,57,58,59,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13,50,51,52,53,54,55,56,57,58,59,60.0,61.0,62.0,63.0,64.0,0.0,0.0,0.0,0.0,0.0
14,1,2,3,4,5,6,7,8,9,10,11.0,12.0,13.0,14.0,15.0,16.0,17.0,18.0,19.0,0.0
15,10,11,12,13,14,15,16,17,18,19,20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,29.0
16,20,21,22,23,24,25,26,27,28,29,30.0,31.0,32.0,33.0,34.0,35.0,36.0,37.0,38.0,39.0
17,30,31,32,33,34,35,36,37,38,39,40.0,41.0,42.0,43.0,44.0,0.0,0.0,0.0,0.0,0.0
18,40,41,42,43,44,45,46,47,48,49,50.0,51.0,52.0,53.0,54.0,55.0,56.0,57.0,58.0,59.0
19,50,51,52,53,54,55,56,57,58,59,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20,50,51,52,53,54,55,56,57,58,59,60.0,61.0,62.0,63.0,64.0,0.0,0.0,0.0,0.0,0.0
21,1,2,3,4,5,6,7,8,9,10,11.0,12.0,13.0,14.0,15.0,16.0,17.0,18.0,19.0,0.0
22,10,11,12,13,14,15,16,17,18,19,20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,29.0
23,20,21,22,23,24,25,26,27,28,29,30.0,31.0,32.0,33.0,34.0,35.0,36.0,37.0,38.0,39.0
24,30,31,32,33,34,35,36,37,38,39,40.0,41.0,42.0,43.0,44.0,0.0,0.0,0.0,0.0,0.0
25,40,41,42,43,44,45,46,47,48,49,50.0,51.0,52.0,53.0,54.0,55.0,56.0,57.0,58.0,59.0
26,50,51,52,53,54,55,56,57,58,59,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
27,50,51,52,53,54,55,56,57,58,59,60.0,61.0,62.0,63.0,64.0,0.0,0.0,0.0,0.0,0.0

In [16]:
import numpy as np
arr = np.array([1,2,3,4])

In [22]:
arr = np.ones((5,3,4,2))

In [30]:
arr[2,1,:,:]

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

array([], shape=(0, 3, 4, 2), dtype=float64)